export const REGISTER_INIT = 'REGISTER_INIT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FORGET_PASSWORD_INIT = 'FORGET_PASSWORD_INIT';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAIL = 'FORGET_PASSWORD_FAIL';

export const LOGIN_INIT = 'LOGIN_INIT';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const RESET_PASSWORD_INIT = 'RESET_PASSWORD_INIT';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAIL = 'RESET_PASSWORD_FAIL';

export const LOGOUT = 'LOGOUT';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const LOAD_TOURS_INIT = 'LOAD_TOURS_INIT';
export const LOAD_TOURS_SUCCESS = 'LOAD_TOURS_SUCCESS';
export const LOAD_TOURS_FAIL = 'LOAD_TOURS_FAIL';

export const LOAD_SINGLE_TOUR_INIT = 'LOAD_SINGLE_TOUR_INIT';
export const LOAD_SINGLE_TOUR_SUCCESS = 'LOAD_SINGLE_TOUR_SUCCESS';
export const LOAD_SINGLE_TOUR_FAIL = 'LOAD_SINGLE_TOUR_FAIL';

export const CLEAR_SINGLE_TOUR = 'CLEAR_SINGLE_TOUR';
export const USER_DELETE = 'USER_DELETE';

export const USER_LOAD_INIT = 'USER_LOAD_INIT';
export const USER_LOAD_FAIL = 'USER_LOAD_FAIL';
export const USER_LOAD_SUCCESS = 'USER_LOAD_SUCCESS';

export const USER_UPDATE_INIT = 'USER_UPDATE_INIT';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const GET_BOOKED_TOURS_INIT = 'GET_BOOKED_TOURS_INIT';
export const GET_BOOKED_TOURS_SUCCESS = 'GET_BOOKED_TOURS_SUCCESS';
export const GET_BOOKED_TOURS_FAIL = 'GET_BOOKED_TOURS_FAIL';

export const BOOK_TOUR_INIT = 'BOOK_TOUR_INIT';
export const BOOK_TOUR_SUCCESS = 'BOOK_TOUR_SUCCESS';
export const BOOK_TOUR_FAIL = 'BOOK_TOUR_FAIL';

export const GET_ALL_REVIEW_FAIL = 'GET_ALL_REVIEW_FAIL';
export const GET_ALL_REVIEW_INIT = 'GET_ALL_REVIEW_INIT';
export const GET_ALL_REVIEW_SUCCESS = 'GET_ALL_REVIEW_SUCCESS';

export const ADD_REVIEW_INIT = 'ADD_REVIEW_INIT';
export const ADD_REVIEW_SUCCESS = 'ADD_REVIEW_SUCCESS';
export const ADD_REVIEW_FAIL = 'ADD_REVIEW_FAIL';

export const UPDATE_REVIEW_INIT = 'UPDATE_REVIEW_INIT';
export const UPDATE_REVIEW_SUCCESS = 'UPDATE_REVIEW_SUCCESS';
export const UPDATE_REVIEW_FAIL = 'UPDATE_REVIEW_FAIL';

export const UPDATE_TOUR_INIT = 'UPDATE_TOUR_INIT';
export const UPDATE_TOUR_SUCCESS = 'UPDATE_TOUR_SUCCESS';
export const UPDATE_TOUR_IMAGES_SUCCESS = 'UPDATE_TOUR_IMAGES_SUCCESS';
export const UPDATE_TOUR_IMAGES_FAIL = 'UPDATE_TOUR_IMAGES_FAIL';
export const UPDATE_TOUR_FAIL = 'UPDATE_TOUR_FAIL';

export const CREATE_TOUR_INIT = 'CREATE_TOUR_INIT';
export const CREATE_TOUR_SUCCESS = 'CREATE_TOUR_SUCCESS';
export const CREATE_TOUR_FAIL = 'CREATE_TOUR_FAIL';

export const DELETE_TOUR_INIT = 'DELETE_TOUR_INIT';
export const DELETE_TOUR_SUCCESS = 'DELETE_TOUR_SUCCESS';
export const DELETE_TOUR_FAIL = 'DELETE_TOUR_FAIL';

export const DELETE_REVIEW_INIT = 'DELETE_REVIEW_INIT';
export const DELETE_REVIEW_SUCCESS = 'DELETE_REVIEW_SUCCESS';
export const DELETE_REVIEW_FAIL = 'DELETE_REVIEW_FAIL';
// export const BOOK_TOUR = 'BOOK_TOUR';
